version: "3.8"
services:
  mongodb:
    image: "mongo:5.0"
    container_name: mongodb
    volumes:
      - notes:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=meku
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: <PASSWORD>
    env_file:
      - ./env/mongo.env
    # networks:
    # - meku-net

  backend:
    build: ./server
    container_name: backend
    # build:
    # context: ./server
    # dockerfile: Dockerfile-dev
    # args:
    # some-arg: 1
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./public
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./public/src:/app/src"
    # stdin_open: true (means -it in Docker commands)
    # tty: true (means -it in Docker commands)
    depends_on:
      - backend

volumes:
  notes:
