version: "3.8"
services:
  mongo:
    image: "mongo:5.0"
    volumes:
      - notes:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meku
      - MONGO_INITDB_ROOT_PASSWORD=admin
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: <PASSWORD>
    # env_file:
    # - ./env/mongo.env
    # networks:
    # - meku-net
  # backend:
  # frontend:

volumes:
  notes:
